hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "e201fa917ffd624e255599c43a51dd0e1450b20a587d88086a7c4aa5e16ffaf9"

[[files]]
file = "config/crash_assistant/lang/README.md"
hash = "bd2631461374ee995478917064980edee09d5c300dfde1548264c1d9b6763349"

[[files]]
file = "config/crash_assistant/lang/en_us.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/ru_ru.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/zh_cn.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "e991d9d5def8431a7a765da06eafc9c59f2911a8b39c4d483f96ff8eb0a57560"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "ac39420512ece55a61087db09fe6c4375aa8bd02966b78716c3e3e404938f693"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "9a2fac8d6897a217b507c12612f365eadfaf2db4d84994abdeba8d93877f2152"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "ddd9316b8053dc121ef511d953e2b6a9fa158e296bc80fb663cc4256d790dd20"

[[files]]
file = "config/nostalgic_tweaks/backup/nostalgic_tweaks-client-startup_backup.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/nostalgic_tweaks/nostalgic_tweaks.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "configureddefaults/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "configureddefaults/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "configureddefaults/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "configureddefaults/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "configureddefaults/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "configureddefaults/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "configureddefaults/config/cpm.json"
hash = "3870f1965e60dc67b321c224c41868293c75a595c4f510b2edcff879b7372775"

[[files]]
file = "configureddefaults/config/craftpresence.json"
hash = "616adff7c23266696effd21b205000087433333b99f689ca25e65520012324b2"

[[files]]
file = "configureddefaults/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "configureddefaults/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "configureddefaults/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "configureddefaults/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "configureddefaults/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "configureddefaults/config/lambdynlights.toml"
hash = "40413b8a4f6d5495dc689ab7d812f867f7d07f3696a5a985432e93e7cda9a3db"

[[files]]
file = "configureddefaults/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "configureddefaults/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "configureddefaults/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "configureddefaults/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "configureddefaults/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "configureddefaults/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "configureddefaults/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "configureddefaults/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "configureddefaults/options.txt"
hash = "74dd4f49660613476a80e9137349f512346b6bec5298e793ece0225c1d2d00ad"

[[files]]
file = "configureddefaults/resource_albums.json"
hash = "ecd81924a3b2ad635ddbeef550da86d325300a88ecd133daa70de8c3ed6c9242"

[[files]]
file = "configureddefaults/resource_albums/minecraft.json"
hash = "6ffe86ea7cb0eb66f6f19797140d1bbb7d7ff39d8ab57006f06c2df97e83e362"

[[files]]
file = "configureddefaults/resource_albums/minecraft_classic.json"
hash = "56b2d1a673da56a2a874284efb869eda80f4cbccf3012292797df0736762ed54"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "8c4331db97ea226530fcbb99c18db9ed9d1f54e6447c2a297e898bd8f697f6a2"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "95f5e17cf5ef864ec221bce159f9a3ba20567a82df0b3e8079dc00b6497bb524"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "4787f85c589daa3354184f46392382f017ac7172f543f22504ce5b8755f6f025"
metafile = true

[[files]]
file = "mods/bigshot.pw.toml"
hash = "6c0b36be8537dba425024461724992b2d45b444a7c1345ff4a1d00c87604b7dc"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "c03db130a2fa422bf31b1ffdf598c79b49795b9e0eaff59efff8254d9bc17fea"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "032af7037fd8fd4f708ede54444a2b6107e75aa846db21c5a55cecd397c564cb"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "0dd83155868dc565552f8ddc313aede3094d3523492f52822ffa341288fc2fc9"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
hash = "558e7e2a556d46b24fba83602f413500a4575f1838e48acb43efccf329b40a17"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "47623f35fd6bfdc203656f75b2400708109fb36782f5aa82008039d112d788e4"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "b4bc231191af9af06fc9f33df9140d0505112202e47bb3c55270479a6b17a9c8"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "df4e3de1d55d3b06b47a18a61d64c6e9fb6a8cf483fa2ff09a46bf5ff40f8cb6"
metafile = true

[[files]]
file = "mods/custom-player-models-fabric.pw.toml"
hash = "8105825654be1ac299ff6b409065a91bea3f5496eb7093ecd2f12bccf3af5484"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "fcd6ac00c330b4d90b46e4d6906a3dc4ff64b25625f54fe5fe0b128a5cd3c863"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "55d9fb4d344979174c63eec70bb1139eab91243d6088eaa82d07ee1f5f2828a3"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "0b6b2be912fce39c9e40e7d1cbc2fa8ff3e646626ae043d29c0ae934adc6f4e5"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "f3b89ee3f8a91223837a108c3f63ff33d97036a68a27ebbeefb9613c3fcf6e0d"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1f005cfa3ecb3c99b1cbe4e339beb74d17e334839384f61899376a2481c691f1"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "e79d224bd664cd189049b6a91b677e2ea6cbc6e27da026c44d73b66cca4d8dc0"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "95ab36f6e7274912947f73edfcd97c5c55ee9b85677184a159abda87961d8c64"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "4c232e2680ad8bb2b06cdd4c8531d19eaa64a361107c69eb7a06d4e7dfd376fe"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "9e6c94b982db7244d7bcbb2f90e65d5778a9e7d123ab34ae1e190eb88405b9c9"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "48f8ca009db92b23ea56c3699e1939dbba14d85f99e11a36c6fec1afc4f5df14"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "f6699bfd27a089571477770e4130c5c5c6429e7d3398934c9ba0d9c4c9b74432"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "21829fcfe024c31224f945753671b15923aeb59d199dc771cc8773f4da81992e"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "9b38b604a7475e8cf3f099c1117598ede3e9dc3588f3c02dce902c783847d090"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "85126c8eec99ce702d2ad00876290834907e90e9973391c94606cc3984ab4efd"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "2569a3872f25279f15530a743bf9cba472b4b458c3b3b2a8cf5e37639569df46"
metafile = true

[[files]]
file = "mods/legacy-minecraft.pw.toml"
hash = "fdc885b61eb3ff00afc54a18b5de244394473096db2c488c1747e72d92bc8cb7"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "2497c823910ad053c04b83c195806e1a1f1e42a8276350f2c854a9091e706c03"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f1e11c6d565cc8b8c6962cde70820e8d3f3b9abad851ef4ddf5f467dc1e272da"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "792a5f0fe941e7c9175cb7234b025c1e661a65f3d7272c1fc4cf8cea4015036e"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "427971d0363f92b6cf0f7462c10c440e788971b03280a6fd71aefb59ec4202f7"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "867bc8c6744ec9b3cbaad5125f1130dba1a5ce1b1f47c090e2dca71c4ecf64cd"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "14622ee629c73092383d44247f21150a22e5022c72f2a0f0484b454815433c50"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "c97e40e9cb7705398823566bfed965fc7c2fc16456ac696f387dbe50f3f780b7"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "a8eaf302915b702e8f86a191b01ec59594b3450cf78ba0f7dd353f6c0dd5dbac"
metafile = true

[[files]]
file = "mods/nostalgic-tweaks.pw.toml"
hash = "c67c982ce530c0f21d90b630f006aa92f054de588c27dcf2d9e95b3bf847b116"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "e0899ece330645744ffa107c994f5684ec24edc22d01e370d3db08abb65aa9bb"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "51d31a32aae0e1cac8e6084472d9ee8bd308165e353060075413b9ff5811aac2"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "d3cef8e44e7f4ca364b7af25740ad5c2a29c14ce9f9847a31f386ce6801ef2ca"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "d88cd6f94947541e635993e458c7bbe3a33ee4371374b69fc763b570fa051417"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "37e917db3cddb70bfdecc62917d37091238f1826ee4630a2ecd381c995ad2ca9"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "ab0970dab91433714f2645b5c62474f7fc4146b18db09a88a32f27b1c10cc39f"
metafile = true

[[files]]
file = "mods/wi-zoom.pw.toml"
hash = "eb9f2d699bd472dfda5d06f52b0f0ac0a86abc79ee0bfbafd9ee06741b2966a7"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f77b42acff060e866a9c09b31d232ea5eda3286b0d25ce1083b2c96b32ef403d"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "1fa2c4e4a06b1d972ad6374da4b0f295e70940f51aae0d48d54819f4f1deb3f8"
metafile = true
