hash-format = "sha256"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "72601a9c04c5e2ebadc0f7dba9abe2bcc87f5056be9beb90cf37054f33f486b0"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "508aee91243a721cfa5532564e3b4ea82ca868167811a73b00776673b7402d0a"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "20a7c9a9d1ec3c730f37af63357d6847afbb28fd37cd13657928c3d22feb055c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "config/yosbr/options.txt"
hash = "cfd15bd7cf3b9570c62f5d909136c886a3da3ca71f3dd1b2fb90d4ed21852452"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "501acdaa439603e3a002cd2da5aad794ff9f39b2c75270bfab5779e2d7c6e0d8"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "62c99a9cf83e5f6ae2c701bafe09b12b31c59d215194d56c7bb9e7ef6f291928"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
hash = "3b69c91eff104ffb4d12f6edbe26bf9055b268fea5473352e6fe719be5420e23"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ce0b6c452313b669ce95d6bc7f232f72b89bf61ebb2013cac5b17a09c8132510"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "0b40c584f98d0cbeabe1d5842fffe6b5785a15fd8bc8ae702dc90cf431254326"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "9f41b9749625cd883ec21fa681108eeae1356421907acf63ba3570365b097322"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "67099bc47fc849c2964b3b64b6f3af6fcbf941d9a4f1c03dda25f746b279015b"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c56ddfdfccf143c8c6b5b93e9555d1c2d80ff7c1bdacd91dfede65785fa686b0"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "2cb0e7200dfbd40e66d234c289108b3791feef74b5a856416cb54b52ffc32f24"
metafile = true

[[files]]
file = "mods/legacy4j.pw.toml"
hash = "0cc5218a41f7ad0db5515ff643723f68048c6426ce1047035ba99554a1e7ce49"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a08a445002542d96a8481654c3f4b5e2d3c064f77b477aeaa3a1d1c3cd396ca8"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "936f8e3b23ec686afb7bf7f379984662f44099bc54f11767445ef2bd3e70fde7"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "f4b9d7acc345b8df6dd13e19b36658cbca476abdee703ee6f38c66d33e8fa763"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "058f62395b41a3b18121bcd961320cc8fd8460a34a5ccb4f07552e42ff19df4a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "53b00436579bd2ea920ef8ae8b1464cb4744dbfd21055d8a3f4768019b78e5bc"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "ff2f782be8090072041d0cd00abed11c1a22dfe2d397cd73e042f3b449954588"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "3fdbd6ec9aaff3bc16c2206c64ec38e81b167e1736ab24840a2d0e9247263863"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/legacy-skin-packs.pw.toml"
hash = "c3eb9ba696a1afe5d1cd4091822b4d5fb096c1d5995b6e093b793d8681bef99a"
metafile = true

[[files]]
file = "resourcepacks/legacy-skins-pack-ordering.pw.toml"
hash = "9243fdbcadf7f6bf5a32f2b73e50ce7d374f99b685a7d1d5cf77c1ec76f60c46"
metafile = true

[[files]]
file = "resourcepacks/legacy-worlds.pw.toml"
hash = "aed5efab46de12e572df2b7f73173d7536552b941d796ca7afea7d8218c6afa1"
metafile = true

[[files]]
file = "resourcepacks/modern-skin-packs.pw.toml"
hash = "9987bf67fffa8d63ddd4752e4d641f126c14fdbec6f1dff6ef6dee5869f55982"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "0e0d1d8f83c5af75781b11907ff1d52737f4fcfb7786ed16d69b31c4fce26f48"
metafile = true
