name = "Re-Console"
author = "omo50"
version = "2.6.0+mc1.21.4+fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c8b33adc57c77fc1025ad85f6971d6ea7c71af6d30c44a681a5f90460bfbe72"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
