name = "Re-Console Lite"
author = "omo50, JacksTheGreat, Technocality"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "407601c0331f893607940874938f707733e4f982f7759898fc4bbc03202f2531"

[versions]
fabric = "0.16.14"
minecraft = "1.21.3"
