hash-format = "sha256"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "72601a9c04c5e2ebadc0f7dba9abe2bcc87f5056be9beb90cf37054f33f486b0"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "508aee91243a721cfa5532564e3b4ea82ca868167811a73b00776673b7402d0a"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "20a7c9a9d1ec3c730f37af63357d6847afbb28fd37cd13657928c3d22feb055c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "config/yosbr/options.txt"
hash = "cfd15bd7cf3b9570c62f5d909136c886a3da3ca71f3dd1b2fb90d4ed21852452"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "e8889bde7505804ed423efffbfd725be4784ac1281d69ef97599c066cc3f5c1e"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "fbe6c7118922a86bb401c72b721d69c60cc0af09c74061d957b99c58821f9693"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "287209b1b1b7c27f11f59ef3eda5fb5f4431aa6b51701870a426c0b39da74fce"
metafile = true

[[files]]
file = "mods/custom-player-models-fabric.pw.toml"
hash = "37b500b480056c8f3799a2862b5e158b90acd5cb2d12e797bf29252455c78e00"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "532f682da1652b2918b742b01fab0ee5980b87f181c641dcccfecc0ba044ecc7"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "092c3d73d2457a5c77e3ade8dd83b26d3714f1853de53298b74901eacaeb1988"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7e103db4e27121c3c96b490b67da24059a8d90e1b5ba44898c49b3999a7b4f2b"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "10ca18a3ecc1f43ed7e23c3483ef8823756744628fe59a7c32918106f81961b5"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "3dcc43cbc807ec49377efe574b4670ee91e62474aee1bcd068495adea8bc1f6a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d356894332edc73db729d66be34e0d58a8cabd4daa5b8ec00d272d1f21788655"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8629101cb27dad1f32f622d0dc8dfdf9583caee5a7e7a75524284aea2d09daa7"
metafile = true

[[files]]
file = "mods/legacy-minecraft.pw.toml"
hash = "55b44e8b277a98884cac439e6411793134f1119c67e5ad00d3713301acb9ad19"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "dd156d0cdaa67cc674d036f388dc153da5aa21c00214297b94234b9ac7d5b54e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "29d81a30d4acfc46fda4cfa4c40e57b49ce9823796b3b173daf059f679c2b675"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "229d1eabf82bea64acb5421ff045294b895340fd4e44b80817b143a54d76126a"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "580db1cc3b78cbafc48cf9be4bd5d478fdddb454b12b519593240f68f896dd89"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "69ff63802caa2618d8323454c315a17cc6f0a433ad19d0158ebcb5b746e9cfd2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "2bbbe84ce305111cb5cd483ddb75497da9fac5e29074ba527fcbb719c8f5e8f8"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "a6a34f29d67e4f7c584eadeae26a2552921b6d51293a964b59c091e5f5896ca5"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "44884083814b7aac7697630e19a182f8b1a48c1479dc645b0876b6e62fc2cc0a"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "resourcepacks/legacy-skin-packs.pw.toml"
hash = "c3eb9ba696a1afe5d1cd4091822b4d5fb096c1d5995b6e093b793d8681bef99a"
metafile = true

[[files]]
file = "resourcepacks/legacy-skins-pack-ordering.pw.toml"
hash = "9243fdbcadf7f6bf5a32f2b73e50ce7d374f99b685a7d1d5cf77c1ec76f60c46"
metafile = true

[[files]]
file = "resourcepacks/legacy-worlds.pw.toml"
hash = "aed5efab46de12e572df2b7f73173d7536552b941d796ca7afea7d8218c6afa1"
metafile = true

[[files]]
file = "resourcepacks/modern-skin-packs.pw.toml"
hash = "9987bf67fffa8d63ddd4752e4d641f126c14fdbec6f1dff6ef6dee5869f55982"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "0e0d1d8f83c5af75781b11907ff1d52737f4fcfb7786ed16d69b31c4fce26f48"
metafile = true

[[files]]
file = "servers.dat"
hash = "039bc2e0eaa0d8eb95dcfaf5ea4c025a1333cfcd46a86ada507f5319d392fbab"
