hash-format = "sha256"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "72601a9c04c5e2ebadc0f7dba9abe2bcc87f5056be9beb90cf37054f33f486b0"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "508aee91243a721cfa5532564e3b4ea82ca868167811a73b00776673b7402d0a"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "20a7c9a9d1ec3c730f37af63357d6847afbb28fd37cd13657928c3d22feb055c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "config/yosbr/options.txt"
hash = "cfd15bd7cf3b9570c62f5d909136c886a3da3ca71f3dd1b2fb90d4ed21852452"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "95f5e17cf5ef864ec221bce159f9a3ba20567a82df0b3e8079dc00b6497bb524"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "5961d49f0b613624392b023279d7d5e2b38eafabf467cee326f52610572887e2"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "0dd83155868dc565552f8ddc313aede3094d3523492f52822ffa341288fc2fc9"
metafile = true

[[files]]
file = "mods/custom-player-models-fabric.pw.toml"
hash = "8105825654be1ac299ff6b409065a91bea3f5496eb7093ecd2f12bccf3af5484"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "fcd6ac00c330b4d90b46e4d6906a3dc4ff64b25625f54fe5fe0b128a5cd3c863"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "55d9fb4d344979174c63eec70bb1139eab91243d6088eaa82d07ee1f5f2828a3"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ffb0ec9ff26e7c110ce3f0acaaa2f70bb319a245f99b1bb6614eb1ba42ab57b3"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1f005cfa3ecb3c99b1cbe4e339beb74d17e334839384f61899376a2481c691f1"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "4c232e2680ad8bb2b06cdd4c8531d19eaa64a361107c69eb7a06d4e7dfd376fe"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "48f8ca009db92b23ea56c3699e1939dbba14d85f99e11a36c6fec1afc4f5df14"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "f6699bfd27a089571477770e4130c5c5c6429e7d3398934c9ba0d9c4c9b74432"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a4a9b9adba2d1ba9f3be438a1b304d293b02034c9217496ed7deafb91bcbf4ee"
metafile = true

[[files]]
file = "mods/legacy-minecraft.pw.toml"
hash = "fdc885b61eb3ff00afc54a18b5de244394473096db2c488c1747e72d92bc8cb7"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "2497c823910ad053c04b83c195806e1a1f1e42a8276350f2c854a9091e706c03"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f1e11c6d565cc8b8c6962cde70820e8d3f3b9abad851ef4ddf5f467dc1e272da"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "867bc8c6744ec9b3cbaad5125f1130dba1a5ce1b1f47c090e2dca71c4ecf64cd"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "9136836f8674011a21081263debf30a0d2442ef28438317965cb0df9c0554631"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "a8eaf302915b702e8f86a191b01ec59594b3450cf78ba0f7dd353f6c0dd5dbac"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "04d27de146b8f315668b9fe23ffdfd768c8ade8b6a1c8a9fa5831c23d35e8ca3"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "37e917db3cddb70bfdecc62917d37091238f1826ee4630a2ecd381c995ad2ca9"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "435f2b78dca925371c1dcbdca15bd1d2cfa26a6e827f5b9439e6dcbbb3685397"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f77b42acff060e866a9c09b31d232ea5eda3286b0d25ce1083b2c96b32ef403d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "resourcepacks/legacy-skin-packs.pw.toml"
hash = "c3eb9ba696a1afe5d1cd4091822b4d5fb096c1d5995b6e093b793d8681bef99a"
metafile = true

[[files]]
file = "resourcepacks/legacy-skins-pack-ordering.pw.toml"
hash = "9243fdbcadf7f6bf5a32f2b73e50ce7d374f99b685a7d1d5cf77c1ec76f60c46"
metafile = true

[[files]]
file = "resourcepacks/legacy-worlds.pw.toml"
hash = "aed5efab46de12e572df2b7f73173d7536552b941d796ca7afea7d8218c6afa1"
metafile = true

[[files]]
file = "resourcepacks/modern-skin-packs.pw.toml"
hash = "9987bf67fffa8d63ddd4752e4d641f126c14fdbec6f1dff6ef6dee5869f55982"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "0e0d1d8f83c5af75781b11907ff1d52737f4fcfb7786ed16d69b31c4fce26f48"
metafile = true
