name = "Re-Console"
author = "omo50"
version = "2.2.0+mc1.21.1+fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79eff49924d0c08a1758426cb5c994a6dbf9c97cf442c572d82e3df9ae22bb30"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
