hash-format = "sha256"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "72601a9c04c5e2ebadc0f7dba9abe2bcc87f5056be9beb90cf37054f33f486b0"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "508aee91243a721cfa5532564e3b4ea82ca868167811a73b00776673b7402d0a"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "20a7c9a9d1ec3c730f37af63357d6847afbb28fd37cd13657928c3d22feb055c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "config/yosbr/options.txt"
hash = "cfd15bd7cf3b9570c62f5d909136c886a3da3ca71f3dd1b2fb90d4ed21852452"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "1e59464196bd2a0cb5dcc4eb6014e323982e993c68c0f0173ff95b58ceed366e"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "782209127aea1b0a5fbac71706b5d0fc7de4882c5b643512937afc0d06e8ad86"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "4700fcc4fa1f3565cf3ef54dad8673bc940d83652b07dd2461c88b4a5b38aa16"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
hash = "735a44bfa99dbb8857ff2be4b9e967ec0db1deaf814a28f19fe5838dfe77fbe3"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "04851cf23a0fef9e213180bf5926b705c5ad2d0b04d41934b915cc1ccfabd841"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "61d64eadda8079ccd7c906a3b5143ab5b9b3716918c775dad2d3d59dfbe7bb41"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "f83de366b76a05a3347eb535d7653451066715fec9939d0d696b7f527887aa7a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "003dc0c0b378d7c0a3b80ed9edf317cedb95651d3b2c6d317c678dd75c498479"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "562cf98ebc306af21ca71cd23b9cfb54e47ea0243f7c53da79b32136b7f4da78"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "bfd0e9e0e3ba950e458caf9687e2ebbf0a3c4e1f2f97259a25242f5649e808a9"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2556b7562df149e51866d07f97e29909dc98d1528fb656ad2cc64fe4ee60091b"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2b699ec9fd674b493af0e52bc3ecbbdb3dc890a6d70f132dc146d5331c0d5b28"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "ef47659617e6f5ca961b4227cf656676a4a3f42844eea939b41ea1751037d9a5"
metafile = true

[[files]]
file = "mods/legacy4j.pw.toml"
hash = "9e59105e02fbbe0dd484b31145918479ea574731e110939a2022aadc5f5e9c81"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "da82ef9cb9353b9ff2701172e56618a60a357bfee92d1c97a875a5d835a6cdc9"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "fa01d0d1b480410d3b46647b676849a7c266a9a9c0fdf444cbf80eb56a559d92"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "03b88e6c07796d391b9ea91b68af2a0bc3bf66b87d7f1faa298d581be40cc365"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "8724da09ac15ed3b82a72aaebd2343101a898f3e611cb6adc0ff65a27981fa5d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c7c6894d207ecc12adcce8cb6e4128543d0799c94e0245d935a3419ea0c29f36"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "58c228419129120ffe14b85a5f154de00fdc6be96db8c60373ee5b6f11d261b2"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ab6a2a1848c9ea16c231c6f35408996302dacd101f3d14104b101edb10870ec3"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/legacy-skin-packs.pw.toml"
hash = "c3eb9ba696a1afe5d1cd4091822b4d5fb096c1d5995b6e093b793d8681bef99a"
metafile = true

[[files]]
file = "resourcepacks/legacy-skins-pack-ordering.pw.toml"
hash = "657e310ef05e0e0a3f7a81f2f6a2b6b08e04c9ec833ae5aad80de817c5a4d7ad"
metafile = true

[[files]]
file = "resourcepacks/legacy-worlds.pw.toml"
hash = "aed5efab46de12e572df2b7f73173d7536552b941d796ca7afea7d8218c6afa1"
metafile = true

[[files]]
file = "resourcepacks/modern-skin-packs.pw.toml"
hash = "9987bf67fffa8d63ddd4752e4d641f126c14fdbec6f1dff6ef6dee5869f55982"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "0e0d1d8f83c5af75781b11907ff1d52737f4fcfb7786ed16d69b31c4fce26f48"
metafile = true
