name = "Re-Console"
author = "omo50"
version = "2.6.0+mc1.20.1+fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a62ddbe728c5f56d49ed02f9cc6cc0046ab3be473bb953a6af486c2457caa69"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
