hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "e201fa917ffd624e255599c43a51dd0e1450b20a587d88086a7c4aa5e16ffaf9"

[[files]]
file = "config/crash_assistant/lang/README.md"
hash = "bd2631461374ee995478917064980edee09d5c300dfde1548264c1d9b6763349"

[[files]]
file = "config/crash_assistant/lang/en_us.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/ru_ru.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/zh_cn.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "e991d9d5def8431a7a765da06eafc9c59f2911a8b39c4d483f96ff8eb0a57560"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "ac39420512ece55a61087db09fe6c4375aa8bd02966b78716c3e3e404938f693"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "9a2fac8d6897a217b507c12612f365eadfaf2db4d84994abdeba8d93877f2152"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "ddd9316b8053dc121ef511d953e2b6a9fa158e296bc80fb663cc4256d790dd20"

[[files]]
file = "config/nostalgic_tweaks/backup/nostalgic_tweaks-client-startup_backup.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/nostalgic_tweaks/nostalgic_tweaks.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "configureddefaults/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "configureddefaults/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "configureddefaults/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "configureddefaults/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "configureddefaults/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "configureddefaults/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "configureddefaults/config/cpm.json"
hash = "3870f1965e60dc67b321c224c41868293c75a595c4f510b2edcff879b7372775"

[[files]]
file = "configureddefaults/config/craftpresence.json"
hash = "616adff7c23266696effd21b205000087433333b99f689ca25e65520012324b2"

[[files]]
file = "configureddefaults/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "configureddefaults/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "configureddefaults/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "configureddefaults/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "configureddefaults/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "configureddefaults/config/lambdynlights.toml"
hash = "40413b8a4f6d5495dc689ab7d812f867f7d07f3696a5a985432e93e7cda9a3db"

[[files]]
file = "configureddefaults/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "configureddefaults/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "configureddefaults/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "configureddefaults/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "configureddefaults/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "configureddefaults/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "configureddefaults/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "configureddefaults/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "configureddefaults/options.txt"
hash = "74dd4f49660613476a80e9137349f512346b6bec5298e793ece0225c1d2d00ad"

[[files]]
file = "configureddefaults/resource_albums.json"
hash = "ecd81924a3b2ad635ddbeef550da86d325300a88ecd133daa70de8c3ed6c9242"

[[files]]
file = "configureddefaults/resource_albums/minecraft.json"
hash = "6ffe86ea7cb0eb66f6f19797140d1bbb7d7ff39d8ab57006f06c2df97e83e362"

[[files]]
file = "configureddefaults/resource_albums/minecraft_classic.json"
hash = "56b2d1a673da56a2a874284efb869eda80f4cbccf3012292797df0736762ed54"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "34e84fe06c202a2f3a9c19e8a21d394532d8f7ecf6b91c4a2074fbebefb359da"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "e8889bde7505804ed423efffbfd725be4784ac1281d69ef97599c066cc3f5c1e"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "32c999c51a6c62ab3a688322c738ee248a97632c632c9f089727f2e85a6ffcfe"
metafile = true

[[files]]
file = "mods/bigshot.pw.toml"
hash = "a87b05b2c5487809936c54baa518a724672b3f03bb2b1ec49d0c8a936c1489a1"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "99e7a43ab11d542f3f26b22e34a3784abaa5b0ac15e732aa067f13ff9240226b"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "c1f9b085d63a6647137d54d7335c9051039ec7abc1c7ec1e3acaa59e23cb7f3b"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "ca43068362e583f873dd90bb182d50b14ed9a9ebf8ece3260a90b0e429a3530e"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
hash = "d84332096011f889a6d8a496a373487ae3c3b3e9e82b4f228f22f554b9bc13c9"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "5db358ca1282b0c27e5a66821fde84f890568db69b2a4e7f6e5a36fe7f7834ba"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "2ff5b1badc831256f08dcbf046d75aea24dd7190df9ed3aa3ce9883d35940d86"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a65c7114e3d56277e74f4426ca5b9a76e0d910daa3abd1a093d72893ad2ddf6d"
metafile = true

[[files]]
file = "mods/custom-player-models-fabric.pw.toml"
hash = "da220d1bddaadec9494e7209aa25e0597f7a46950a49b580b9ad25d7a6c8838b"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "e16c26ac10ff25c1f5c2ac142a50b226f36ca74d755ffa324777b5eae62ef785"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "16de2da70d4614c7bd17d65d949b15a52a3cb39bcc429816b28e994b47149641"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "3816f7b1172710a4138ecf1f78d06e754a83990468ae1097f5ebb44a47387897"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9ed5b17fc03b16f2399a5c6d636aa8c4d9d151d690b307a0cb27f108d8c1404b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "e79d224bd664cd189049b6a91b677e2ea6cbc6e27da026c44d73b66cca4d8dc0"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "440a8c60841d91069a1e7e73f2d59080156728bb4f149b3e40cbd0aa3cb768ec"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "0237d90d53c2b4738cd6021bc0667a53e20fd333d4ae695e256f44f81ce9607d"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "cafd1dc3ef24a06de108c3306a02530c22aa5aa3e68ee70824a55fcdbb78d744"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "e355f5d23c8b7c0ece9f3097c589888f26219b29ddacd00212e750ee381497de"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "16d275acce4553e50f871ef64cf03c49bfdef72d44f4f914a81957085c997491"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "2f37d22ac381690f907bd6c94a4507cd79ca61aed92a19072a1fc2dcc61a3bdd"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "25508b3fb5a69940e3fb652ca2fb4d2d628340fe0958f0681fe87006491ca80c"
metafile = true

[[files]]
file = "mods/legacy-minecraft.pw.toml"
hash = "67a639615be49b08cbe7eee16890367aa94613f296e84a0d032b97fdf42f2b5b"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "f3e8ebe6c2c2182f04bf132c8b7739ac2deaddd7d35bb085c487bc5d20852f29"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f6510e9df610fbb46d6f93592dc3caaed282355d905574a28eaf5174cdd84a93"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "792a5f0fe941e7c9175cb7234b025c1e661a65f3d7272c1fc4cf8cea4015036e"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "5499f2e6b2ede074cd3710acbbff300dad4923673775b1a7e1b834aa7d33be37"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "dca710c8d665fd10d2564a22f365c47a5df04f71836a69128bdf999621f7ae33"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "d8a7f4537e7a8d0621618f44cb596d084c4ee26e573c56846e72248d6bb65aa7"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "a5c950f53416fd0d794b554cec32de277af5be6826a48808ac7359b713baabd1"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "d621c5623bc711e13098f885b01987017056e092ce4f2e9886fa4ea7764de5a7"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "1c34733124a0547e2262da006c2e907fc5a02af1098f67f8e975becc8e8ecb1d"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "fb3451b130641f0fb927aed54086f61334b51870a185a361cd88839580a9eb3c"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "3710d2e54ae58c17c2d9649db779298a70ad7d65877f403dfd378e34b11f2c79"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "2d26d69c2248b5ed9d35989c7542b89149b652a7feb91f9273e75c868176f417"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1fc7358526b1e34a526b74faca47c9546eb376ee59efb77271bb8ff44b273029"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "e10a0a31239bc6ff1346726780db6bf0b8d3832249e0926d11241a0f376cde7d"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f7cd88edb841aec5e4040918078eba21585a7fc18bb23f0fc9bfd72c9f798263"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "1fa2c4e4a06b1d972ad6374da4b0f295e70940f51aae0d48d54819f4f1deb3f8"
metafile = true
