name = "Re-Console Lite"
author = "omo50, JacksTheGreat, Technocality"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4cb5492306a69ff97b94f755f0f2e6a5553d52b36c828f42fb3696bfd1cdfe5"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
